"""
Baseline retrievers for the Visual HyDE comparison study.

Baselines
---------
``TCDHyDERetriever``
    Textual Chart Description HyDE — a VLM generates a *text* description of a
    hypothetical chart for the query; the description is encoded with CLIP's
    text encoder and used to search the image corpus.  Stays entirely in text
    space; contrasts with Visual HyDE which generates an actual chart image.

``ColPaliRetriever``
    ColPali SOTA baseline — loads pre-computed results from a JSONL file
    generated by the ``vidore/colpali-engine`` library.  Returns empty results
    (with a warning) when no pre-computed file is available, so the rest of
    an experiment can still run.

See Also
--------
- :mod:`visual_hyde.retrieval` — proposed Visual HyDE retrievers
- :func:`visual_hyde.baselines.colpali.run_colpali_inference` — script helper
  that generates the JSONL pre-computed results required by ColPaliRetriever
"""

from __future__ import annotations

from visual_hyde.baselines.colpali import ColPaliRetriever, run_colpali_inference
from visual_hyde.baselines.tcd_hyde import TCDHyDERetriever

__all__ = [
    "ColPaliRetriever",
    "TCDHyDERetriever",
    "run_colpali_inference",
]
